# Site wide configuration

title: "Dillon's Startup Journey"
locale: en_US
description: "Startup stories by Dillon, posted every Monday, Wednesday, and Friday!"
logo:
search: true
url: http://www.dillonforrest.com/startup


# Jekyll configuration

permalink:   :title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Dillon Forrest
  avatar: frantic-raw.jpg
  email: dillon@puzzlelabs.io
  disqus-shortname: dillonsstartupjourney
  twitter: dillonforrest
  facebook: #username
  github: dillonforrest
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: dillonforrest
  instagram: dillonforrest
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
